max_steps = 100

[wandb]
project = "reverse-text"
name = "reverse-text-sft"

[model]
name = "PrimeIntellect/Qwen3-0.6B"
attn = "flash_attention_3"

[model.compile]

[data]
name = "willcb/R1-reverse-wikipedia-paragraphs-v1-1000"
seq_len = 4096
batch_size = 32
micro_batch_size = 4

[optim]
lr = 2e-5

[ckpt]
