## to run on H100
max_steps = 1000
batch_size = 512
micro_batch_size = 2
rollouts_per_example = 16
seq_len = 2048
mask_truncated_completions = false

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-7B"

[sampling]
max_tokens = 1024
temperature = 1.0

[monitor.wandb]

[environment]
id = "medcasereasoning"

[monitor.wandb.log_extras]
interval = 10

[eval]
interval = 50

[ckpt]
interval = 200

