max_steps = 1000

[scheduler]
type = "linear"
warmup_steps = 10

[monitor.wandb]

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-7B"

[model.ac]

[optim]
lr = 1e-6
max_norm = 0.01

[ckpt]
interval = 200